# Generated by Django 4.0.5 on 2022-06-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
        migrations.AddField(
            model_name='project',
            name='lint',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
